name: Docker Model Runner in GHA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install DMR, pull a model, and Run a quick script
      run: | 
        sudo apt-get -qq update >/dev/null
        sudo DEBIAN_FRONTEND=noninteractive apt-get -y -qq install ca-certificates curl >/dev/null
        sudo install -m 0755 -d /etc/apt/keyrings
        sudo curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" -o /etc/apt/keyrings/docker.asc
        sudo chmod a+r /etc/apt/keyrings/docker.asc
        sudo echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu noble stable" > /etc/apt/sources.list.d/docker.list
        sudo apt-get -qq update >/dev/null
        sudo DEBIAN_FRONTEND=noninteractive apt-get -y -qq install docker-model-plugin
        docker model pull unsloth/qwen3-gguf:0.6B-UD-Q4_K_XL
        curl --unix-socket $HOME/.docker/run/docker.sock \
            localhost/exp/vDD4.40/engines/llama.cpp/v1/chat/completions \
            -H "Content-Type: application/json" \
            -d '{
                "model": "unsloth/qwen3-gguf:0.6B-UD-Q4_K_XL",
                "messages": [
                    {
                        "role": "system",
                        "content": "You are a helpful assistant."
                    },
                    {
                        "role": "user",
                        "content": "Please write 500 words about the fall of Rome."
                    }
                ]
            }'
